### ISSUE TITLE
[Bug] Left click transformed into middle click.

### ISSUE THREAD

**Issue by Zhyrclew** [CemraJC/clickfix#7] opened 2018-02-02 14:44 UTC
It happened now a few times, the left click on my mouse (theoretically not modified by clickfix) becomes a middle click, and the regular middle click (modified by clickfix) doesn't respond. The right click is still fine, but there must be other weird stuff going on because the windows taskbar "auto hide" doesn't respond either to the movement of the mouse. It lasted up to 1min and seems to disappear when I spam the middle click.
I've no real proof that clickfix is the software that is causing this issue, but it's the first time in 5-6 years of this mouse that this behavior happened, and it doesn't happen when clickfix is closed. So the odds are pretty high.
Here is my settings panel of clickfix : 
![image](https://user-images.githubusercontent.com/19610808/35738016-cf376eb6-082d-11e8-82ba-5cfcb807845f.png)
The mouse I use is a 5 years R.A.T. 7 MMO with new left&right switches (from a few months), and a very glitchy middle click. The PC runs Windows 10 version 1709.

**Comment by CemraJC** [comment] 2018-02-03 09:33
I really wish I could help with this, but unfortunately there's nothing at all in the code I've written that could cause this to happen. 

If you've determined that ClickFix is the likely cause, then it probably is, but it would be due to internal windows hardware hooks that I don't have control over. Only thing I can think of is that maybe the mouse is sending two signals - left mouse, then middle mouse - straight after each other. The middle mouse overrides the left signal, delay is applied. Depending on the mouse drivers, they could also be getting confused by the large delay you have on middle mouse.

I have noticed strange behaviour myself when operating other mouse-detecting apps that likely use their own mouse interrupt code: programs like the snipping tool have issues I can't fix, and windows taskbar may be another one of these troublesome interrupts. 

All that said, the best I can offer is for you to download the latest release and see if the problem goes away. If it doesn't, then maybe try the click detector at the clickfix.cf website to make sure your mouse is doing what you think it is? (It probably is though.)

If you have any contact cleaner lying around, taking the mouse apart dumping a good spray of that in the middle mouse buttons might help?

-----

I'll leave this issue open for now - let me know of any developments.

**Comment by Zhyrclew** [comment] 2018-02-03 23:54
Wow, I didn't expect any answers honestly, I have opened this issue mostly for referencing purposes, so that others wanting to confirm the origin of the bug could find it. I know that this kind of bugs are not easy to fix.
Thank you for the answer and the advices. I will soon have replacement pieces for my middle mouse switch anyway. I will check that I have the latest version of clickfix, and try to narrow down the strange behaviors when it will happen again.
I discovered&downloaded your soft only a few days ago, and this bug followed right after. I exited the soft during 2 days and didn't experienced once the bug. I just re-launched it, I will post here again if i get more information on it.
I thought that using the "restart" command of your soft would clear things up after the bug, unfortunatly it made things worse with it reoccurring only minutes after. But I still have no clue as to what is starting it.
PS: I had 2.5.1, so i'm switching to 2.6.1. But be careful, the .exe that you link on your website (https://www.clickfix.cf/#download-page-link) is pointing towards the 2.4.1 version.

**Comment by CemraJC** [comment] 2018-02-04 08:24
Hopefully, whether hardware or software, your mouse will begin to cooperate soon!

Thanks for the tip about the website - just fixed it then. 

I'll keep this open, because as you said, it's an unresolved bug (for now) that others could find useful to locate discussion about it.

**Comment by Zhyrclew** [comment] 2018-02-04 18:18
Okay, so I have some more information, it seems like there is a link with my anti-virus, Avira AntiVir (Free). 
I already experienced the bug 2-3 times since I re-opened clickfix, and each time I could hear my fans accelerating. 
This last time I have been able to see what was raising my CPU&GPU usage just the time of the mouse click bug : 
An Avira process taking like 25% of my CPU load, and then some update.exe that take like 15%, 

The bug ended as soon as I tested the middle mouse button on your site, Even if two terminated "update.exe" processes were still listed as taking 10% load each.
Before the bug ended I have been able to test the left click on your site, and I can confirm that it was registered as a normal middle click.

![bugclickfix](https://user-images.githubusercontent.com/19610808/35780708-d2d14912-09df-11e8-9f83-ccac4edbc5e9.png)
![bugclickfix2](https://user-images.githubusercontent.com/19610808/35780709-d2ea14b0-09df-11e8-9329-3d2230a5060e.png)

**Comment by CemraJC** [comment] 2018-02-04 23:31
Hmm you're right: judging from that graph, there does appear to be a correlation between clicking and CPU usage.

It is possible that Avira doesn't like how ClickFix works. Although it's definitely not malicious software, it works by intercepting all the (active) click events and sending its own click events through on a sort of timer. The behaviour of effectively hijacking the mouse (regardless of its beneficial outcomes) is almost certainly something that any antivirus software wouldn't like.

Maybe if you add the clickfix.exe file to the list of Avira's exceptions, the bug will bother you no more?

----

Something interesting about that click log, is how sometimes the down event is unidentified, but the up event is. I'm not certain, but I'm fairly confident that only the down events should register an ID:
![image](https://user-images.githubusercontent.com/9857188/35783635-4175a392-0a56-11e8-80c8-ec1803c896e7.png)

Now, the code is written to detect button ID's for both events (see below), but usually only mouse down has an ID attached.
![image](https://user-images.githubusercontent.com/9857188/35783662-abdd62e2-0a56-11e8-9df7-699b10fea306.png)

It would appear that while the bug is present, the clicks that send IDs to the browser are inverted (mouse up sends the ID). Then, on the middle click that cleared the bug, it sent a down event with ID and each click after follows suit.

I don't have enough info to draw any meaningful conclusion from that though, so I suppose we'll just treat it as an interesting side effect for now.

----

Let me know if adding it as an Avira exception resolves the problem! Hopefully it does.

**Comment by Zhyrclew** [comment] 2018-02-05 00:28
Oh, you're right, it was not a "normal" middle click when it was through the left click... 
Well, at least it proves that I'm not becoming crazy and that there is something going on. I find that it's a fairly difficult bug to show&highlight. 
But as you said, it's not what will tell us how to fix it.

I will add it as an Avira exception. I have already set up the .exe into always launching with admin privileges, in order to make the auto-start feature work smoothly in the program file folder.

Unfortunately, the only way to know if the fix works is to wait until it's highly improbable that I've not  experienced the bug in the time span. 
The occurrences are really disparate... for example since my last message I didn't have it once.

**Comment by CemraJC** [comment] 2018-02-06 08:35
With all that going on in the background, it's pretty likely that something is stepping on something else's toes.

Give it a while, like you said, and let me know if the bug goes away. If it does, great! I'll close this. 
If it doesn't, I'll leave it open (probably indefinitely) so it's easy for others to find.

**Comment by Zhyrclew** [comment] 2018-02-09 01:40
Welp, I thought that was it, but no, it wasn't.
It took 3 days for the bug to re-appear, which is very weird given I was getting it 3-6 times a day when I opened this thread.

The .exe is still in exceptions of my anti-virus, and although I made the bug last 15-20 min, no suspect processes were visible, no impact on my cpu/gpu either.

I can give more details on the symptoms of the bug, but, for me, it's getting more and more blurry, I'd say, don't worry about it and close the thread ^^

Here is a complete (as possible) description of the bug : 

The bug occurs when I'm in chrome (but then that's where I am 99% of the time). 

I first see that there is a problem when i drag the mouse down to open the auto-hidden windows taskbar -which then doesn't open at all, or when I want to click on another tab -which instead of taking me to it, close it as if I'd middle clicked it.

When I get -with macros that are programmed on my mouse, ironically- to clickfix's website, the click log clearly indicate that left and right clicks are registered as middle clicks (with the weird detail that the ID of the click is shown on the mouse up event).
Clicking on another tab with my left or right mouse button does register as a middle click and close it.
But on all the chrome tabs, I can still -without any apparent glitch, use my right and left click registering properly, to open a link, or select text and open context menu.

Yes, I'm saying that on your Clickfix webpage for example, I have no problem to use left&right mouse buttons to highlight text and copy it via the context menu, but when I click on your 'click me' test button, both register as a middle mouse button. So what the clicks register as depends on what I click on.

Finally, as soon as I switch over to any other window than the chrome one, neither left or right mouse buttons register at all (no responses). 
More than that, the mouse cursor moves as usual but does not trigger any 'mouse hover' event/animation. 
The other windows are pretty much not reacting to any mouse event, although windows itself does fine with the mouse cursor movement and all my macros.
If I come back to the chrome window, it's as before, nothing changed.

I tried to terminate my saitek (madcatz) drivers, no difference. 
I tried to terminate Clickfix, no difference. (Yep, it's really making me doubt clickfix as anything to do with it. I will, again, not use it a while (like one week full) to see if I can have the bug to occur at least once when it's not running)
I tried to unplug-replug the mouse, no difference.
The bug disappear as soon as I click the middle mouse button.

**Comment by CemraJC** [comment] 2018-02-10 03:46
This is pretty unusual huh!

Well, regardless of the outcome, thanks so much for your comprehensive reports on the process here. Since the bug is dependent on you clicking the middle mouse, and not at all on any of your computer software, I would be inclined to think this might even be a fundamental hardware issue that's messing with the mouse's brain.

Best of luck with whatever course of action you decide to take, and although this is a pretty interesting bug that _could_ be caused by clickfix, I'll close this issue like you suggested.

I guess we'll put it down as a hardware glitch for now.

Thanks again! Really appreciate it 😄

**Closed by CemraJC** 2018-02-10 03:46 UTC

**Comment by Zhyrclew** [comment] 2018-02-20 16:21
Well, as you can see, it's been now almost two weeks i've not been using Clickfix, and I haven't experienced once the bug. 
I'm now pretty sure Clickfix was causing -partly at least- the bug.
So I did not open this thread and bother you for something that have nothing to do with the soft, yey ! :) Thank you for listening and answering to me.
-
I will now use your soft again : I don't have the switches yet, and the bug is so much less annoying than the bounciness and quadruple clicks of the switch ! ^.^
