### ISSUE TITLE
Cosmetic issue: the text "click the Apply or Ok button" isn't in the right spot

### ISSUE THREAD

**Issue by POTSandSTOP** [CemraJC/clickfix#11] opened 2019-03-20 18:28 UTC
![image](https://user-images.githubusercontent.com/492973/54709684-394f6380-4b03-11e9-9670-2e673c064a04.png)

**Comment by CemraJC** [comment] 2020-08-05 08:49
Thanks for reporting this - not sure how to reproduce this issue, looks like a font is not installed or something?

Closing this for now, if I do a future release I'll try and fix this.

**Closed by CemraJC** 2020-08-05 08:49 UTC
